GET http://localhost:8000/todo
Accept: application/json

###
POST http://localhost:8000/todo
Content-Type: application/json

{
  "id":5,
  "content": "a content for a new example"
}
###

DELETE http://localhost:8000/todo/5
