spring:
  application:
    name: todolist-website
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: application
            client-secret: "b047cc08-f324-4bd4-a7fa-31d8ddbc08e6"
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/website/login/oauth2/code/keycloak
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: "http://localhost:8080/auth/realms/todo-list/protocol/openid-connect/auth"
            token-uri: "http://localhost:8080/auth/realms/todo-list/protocol/openid-connect/token"
            user-info-uri: "http://localhost:8080/auth/realms/todo-list/protocol/openid-connect/userinfo"
            jwk-set-uri: "http://localhost:8080/auth/realms/todo-list/protocol/openid-connect/certs"
            user-name-attribute: preferred_username
server:
  servlet:
    context-path: /website
  port: 3000

todo:
  base-url: http://localhost:8000