apiVersion: v1
kind: Namespace
metadata:
  name: todo-list-website

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: todo-list-website
data:
  filebeat.yml: |-
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: true

    filebeat.inputs:
      - type: log
        multiline.pattern: '^java.|^[[:space:]]+(at|\.{3})\b|^Caused by:|^END:'
        multiline.negate: false
        multiline.match: after

        enabled: true
        paths:
          - /var/log/todo-list/*.log

    processors:
      - add_fields:
           target: application
           fields:
             name: todo-list-website
      - add_cloud_metadata: ~
      - add_docker_metadata: ~

    setup.kibana:
      host: "kibana.monitoring.svc.cluster.local:5601"

    output.elasticsearch:
      hosts: ['elasticsearch.monitoring.svc.cluster.local:9200']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-list-website
  namespace: todo-list-website
data:
  OIDC_IDP_URL: http://local.todo-list.com/auth/realms/todo-list
  OIDC_REDIRECT_URL: http://local.todo-list.com/website/oidc/callback
  OIDC_CLIENT_ID: application
  OIDC_CLIENT_SECRET: b047cc08-f324-4bd4-a7fa-31d8ddbc08e6
  context_path: /website
  todo.base-url: http://todo-service.todo-service.svc.cluster.local:8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-website
  namespace: todo-list-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list-website
  template:
    metadata:
      labels:
        app: todo-list-website
    spec:
      volumes:
        - name: filebeat
          configMap:
            name: filebeat-config

        - name: application-logs
          emptyDir: {}

        - name: application-config
          configMap:
            name: todo-list-website
      containers:
        - name: filebeats
          image: docker.elastic.co/beats/filebeat:7.6.1
          volumeMounts:
            - name: application-logs
              mountPath: /var/log/todo-list/

            - name: filebeat
              subPath: filebeat.yml
              mountPath: /usr/share/filebeat/filebeat.yml

        - name: todo-list-website
          image: mrflick72/todo-list-website:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /usr/local/todo-list-website/application.yml
              subPath: application.yml
              name: application-config

            - mountPath: /var/log/todo-list/
              name: application-logs

---

apiVersion: v1
kind: Service
metadata:
  name: todo-list-website
  namespace: todo-list-website
spec:
  selector:
    app: todo-list-website
  ports:
    - port: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todo-list-website
  namespace: todo-list-website
spec:
  rules:
    - http:
        paths:
          - path: /website
            backend:
              serviceName: todo-list-website
              servicePort: 8080